name = "Micron"
license = "MIT"
licenselink = "https://github.com/wizardfree/micron/blob/master/LICENSE"
description = "Minimalist Hugo Theme"
tags = ["minimal"]
min_version = "0.41.0"

[author]
  name = "Joseph Fleet"
  homepage = "wizardinthe.cloud"